export const usuarios_data = [
  {
    id_user: 0,
    cedula: "1",
    telefono: 1,
    nombres: 'admin',
    ciudad: 'Guayaquil',
    dirrecion: 'admin',
    usuario: 'admin',
    email: 'admin@zinema.com',
    password: '12345',
  },
  {
    id_user: 1,
    cedula: "915985514",
    telefono: 984208352,
    nombres: 'Franco Quimi',
    ciudad: 'Guayaquil',
    dirrecion: 'Sauces',
    usuario: 'hxbaque',
    email: 'hbaqueem@ug.edu.ec',
    password: '12345',
  },
  {
  id_user: 2,
    cedula: "963285514",
    telefono: 984208562,
    nombres: 'Fabrizio Ramos',
    ciudad: 'Guayaquil',
    dirrecion: 'Urdaneta',
    usuario: 'fbrz',
    email: 'mauro.ramosm@ug.edu.ec',
    password: '12345',
  },
]